name = "Strata"
version = "0.1.0"
defaultTargets = ["Strata", "StrataVerify", "StrataTranslate", "StrataToCBMC"]
testDriver = "StrataTest"

[[lean_lib]]
name = "Strata"

[[lean_lib]]
name = "StrataTest"
globs = ["StrataTest.+"]

[[lean_exe]]
name = "StrataVerify"

[[lean_exe]]
name = "StrataTranslate"

[[lean_exe]]
name = "StrataToCBMC"
